import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import styles from "./layout.module.scss";

import { headers } from "next/headers";
import { prisma } from "./prisma";
import { Project } from "@prisma/client";
import ProjectList from "./projectList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = headers();
    // read the custom x-url header
    const header_url = headersList.get("x-url") || "";

    async function fetchData() {
        "use server";

        return await prisma.project.findMany();
    }

    return (
        <html lang="en">
            <body className={`${inter.className} ${styles.body}`}>
                <div
                    id="header"
                    className={styles.header}
                >
                    <h1>Todo</h1>
                </div>
                <div
                    id="nav"
                    className={styles.nav}
                >
                    <ProjectList props={{ projects: await fetchData() }} />
                </div>
                <div
                    id="main"
                    className={styles.main}
                >
                    {children}
                </div>
            </body>
        </html>
    );
}
